// Generated by LiveScript 1.6.0
(function(){
  var express, cors, expressRateLimit, proxy, create, limitConfig, limiter, nodes, rand, selectNode, app, greenlock;
  express = require('express');
  cors = require('cors');
  expressRateLimit = require('express-rate-limit');
  proxy = require('express-http-proxy');
  create = require('greenlock-express').create;
  limitConfig = {
    windowMs: 150 * 60 * 1000,
    max: 1000000
  };
  limiter = expressRateLimit(limitConfig);
  nodes = ['http://116.202.97.194:8545', 'http://116.202.98.159:8545', 'http://116.202.97.194:8545'];
  rand = function(min, max){
    var r;
    r = Math.random() * (+max - +min) + +min;
    return Math.round(r);
  };
  selectNode = function(){
    var r;
    r = rand(0, 2);
    return nodes[r];
  };
  console.log(selectNode());
  app = express().use(limiter).use(cors()).use('/tx/:id', express['static']('./')).use('/address/:id', express['static']('./')).use('/block/:id', express['static']('./')).use('/api', proxy(selectNode)).use('/', express['static']('./'));
  greenlock = create({
    email: 'denis@gmail.com',
    agreeTos: true,
    configDir: './config/acme/',
    communityMember: false,
    telemetry: false,
    app: app,
    debug: true
  });
  greenlock.listen(80, 443);
}).call(this);
